name: Azure Functions CI/CD

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive Function App files
      run: zip -r functionapp.zip . -x '.git/*'

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: '<YOUR_FUNCTION_APP_NAME>'
        package: './functionapp.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
